# Generated by Django 2.1.1 on 2019-01-19 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0013_auto_20190118_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmaster',
            name='under_which_department',
        ),
    ]
