# Generated by Django 2.1.5 on 2019-01-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0015_auto_20190119_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmaster',
            name='objective',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='eventmaster',
            name='rounds',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='eventmaster',
            name='rules',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
