# Generated by Django 2.1.1 on 2019-01-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0016_auto_20190119_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmaster',
            name='objective',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='eventmaster',
            name='rounds',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='eventmaster',
            name='rules',
            field=models.CharField(blank=True, max_length=100000),
        ),
    ]
