# Generated by Django 2.1.5 on 2019-01-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0017_auto_20190120_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmaster',
            name='rounds',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='eventmaster',
            name='rules',
            field=models.TextField(blank=True, max_length=100000),
        ),
    ]
