# Generated by Django 2.1.5 on 2019-01-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0018_auto_20190120_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmaster',
            name='objective',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
