# Generated by Django 2.1.1 on 2019-01-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0019_auto_20190120_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='src',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='eventmaster',
            name='src',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
