# Generated by Django 2.1.1 on 2019-01-21 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0020_auto_20190121_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='src',
            new_name='banner_src',
        ),
        migrations.RenameField(
            model_name='eventmaster',
            old_name='src',
            new_name='container_src',
        ),
    ]
