# Generated by Django 2.1.1 on 2019-01-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0021_auto_20190121_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='GandharvaHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('data', models.TextField(blank=True, max_length=1000)),
            ],
        ),
    ]
