# Generated by Django 2.1.5 on 2019-01-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0024_sponsormaster_sponsor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
