# Generated by Django 2.1.1 on 2019-01-25 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0025_auto_20190124_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='user_coll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='EventApp.College'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='EventApp.Department'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_year',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
